---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

## Metrics

[Introduction.](intro.html)

[Calculating $p$-values: the "implied discrete distribution."](pvals.html)


## Fitting the droplet-based 3' scRNA-seq dataset from Montoro et al.

1. [A preliminary look at the data.](droplet.html)
1. [A comparison of different variance structures.](var_type.html)
1. [An argument for backfitting.](backfit.html)
1. [A comparison of different prior families.](prior_type.html)
1. [A discussion of size factors.](size_factors.html)
1. [A second look at pseudocounts.](pseudocount_redux.html)
    + [Addendum: a simple explanation for the failure of change-of-variables adjustments.](elbo_problems.html)
1. [An attempt to use a low-rank representation of the data rather than the full data.](lowrank.html)
1. [A detailed look at a 30-factor fit.](final_montoro.html)


## Fitting the 3k PBMC dataset from Zheng et al.

1. [An introduction to the dataset.](pbmc.html)
1. [Variance regularization: part one.](var_reg_pbmc.html)
1. [Variance regularization: part two.](var_reg_pbmc2.html)
1. [Prior families.](prior_type_pbmc.html)
1. [Size factors.](size_factors_pbmc.html)
1. [Pseudocounts.](pseudocount_redux_pbmc.html)


## More datasets.

1. [Deng et al.](deng.html)
1. SNMF on data simulated from an NMF model: [Part I.](snmf_on_nmf.html) [Part II.](snmf_on_nmf2.html) 
1. [Nonnegative fits to Deng et al.](deng_nn.html)
1. [Nonnegative fits to PBMCs.](pbmc_nn.html)
1. [SNMF fit to Pijuan-Sala et al.](pijuan_snn.html)
1. [Another Pijuan-Sala dataset.](pijuan_atlas_snn.html)

## Archived

These analyses have not necessarily been updated to use the newest version of `flashier`.

[A brief discussion of Poisson $p$-values.](poisson_p.html)

[An early exploration of pseudocounts.](pseudocount.html)

[An investigation into backfitting flash-drift fits.](drift_backfit.html)

